/**
 * @fileOverview Constantes compartilhadas para inteligência geográfica e política.
 */

export const TOP_61_CITIES = [
  'SÃO LUÍS', 'IMPERATRIZ', 'SÃO JOSÉ DE RIBAMAR', 'CAXIAS', 'TIMON', 'CODÓ', 'PAÇO DO LUMIAR', 'AÇAILÂNDIA', 'BACABAL', 'BALSAS', 
  'SANTA INÊS', 'BARRA DO CORDA', 'PINHEIRO', 'CHAPADINHA', 'SANTA LUZIA', 'BURITICUPU', 'GRAJAÚ', 'ITAPECURU MIRIM', 'COROATÁ', 'BARREIRINHAS', 
  'TUTÓIA', 'VARGEM GRANDE', 'VIANA', 'ZÉ DOCA', 'LAGO DA PEDRA', 'COELHO NETO', 'PRESIDENTE DUTRA', 'ARAIOSES', 'SÃO MATEUS DO MARANHÃO', 'PEDREIRAS', 
  'AMARANTE DO MARANHÃO', 'COLINAS', 'SÃO BENTO', 'SANTA HELENA', 'ROSÁRIO', 'BREJO', 'TURIAÇU', 'PARNARAMA', 'MATÕES', 'ICATU', 
  'PENALVA', 'MONÇÃO', 'SANTA RITA', 'URBANO SANTOS', 'VITORINO FREIRE', 'CURURUPU', 'ESTREITO', 'SÃO RAIMUNDO DAS MANGABEIRAS', 'ANAJATUBA', 'MIRANDA DO NORTE', 
  'PORTO FRANCO', 'PASTOS BONS', 'ALTO PARNAÍBA', 'RIACHÃO', 'CAROLINA', 'GUIMARÃES', 'MIRINZAL', 'PERI MIRIM', 'GODOFREDO VIANA', 'ALCÂNTARA', 'RAPOSA'
];

export const CITY_MAYORS: Record<string, { name: string; gender: 'M' | 'F' }> = {
  'SÃO LUÍS': { name: 'Eduardo Braide', gender: 'M' },
  'SÃO JOSÉ DE RIBAMAR': { name: 'Dr. Julinho', gender: 'M' },
  'PAÇO DO LUMIAR': { name: 'Fred Campos', gender: 'M' },
  'RAPOSA': { name: 'Eudes Barros', gender: 'M' },
  'ALCÂNTARA': { name: 'Nivaldo Araújo', gender: 'M' },
  'BACABEIRA': { name: 'Naíra Gonçalo', gender: 'F' },
  'SANTA RITA': { name: 'Dr. Milton Gonçalo', gender: 'M' },
  'ROSÁRIO': { name: 'Jonas Magno', gender: 'M' },
  'PINHEIRO': { name: 'André da Ralpnet', gender: 'M' },
  'CURURUPU': { name: 'Aldo Lopes', gender: 'M' },
  'VIANA': { name: 'Carrinho Cidreira', gender: 'M' },
  'ITAPECURU MIRIM': { name: 'Filipe Marreca', gender: 'M' },
  'CHAPADINHA': { name: 'Belezinha', gender: 'F' },
  'BARREIRINHAS': { name: 'Vinicius Vale', gender: 'M' },
  'TUTÓIA': { name: 'Viriato Cardoso', gender: 'M' },
  'HUMBERTO DE CAMPOS': { name: 'Luis Fernando', gender: 'M' },
  'GUIMARÃES': { name: 'Magno', gender: 'M' },
  'MIRINZAL': { name: 'Deyvison do Posto', gender: 'M' },
  'PERI MIRIM': { name: 'Heliezer do Povo', gender: 'M' },
  'SANTA HELENA': { name: 'Joãozinho Pavão', gender: 'M' },
  'SÃO BENTO': { name: 'Dino Penha', gender: 'M' },
  'TURIAÇU': { name: 'Edésio Cavalcante', gender: 'M' },
  'ANAJATUBA': { name: 'Helder Aragão', gender: 'M' },
  'IMPERATRIZ': { name: 'Rildo Amaral', gender: 'M' },
  'AÇAILÂNDIA': { name: 'Dr. Benjamim', gender: 'M' },
  'GRAJAÚ': { name: 'Dr. Gilson Guerreiro', gender: 'M' },
  'BARRA DO CORDA': { name: 'Rigo Teles', gender: 'M' },
  'BURITICUPU': { name: 'João Carlos', gender: 'M' },
  'ESTREITO': { name: 'Léo Cunha', gender: 'M' },
  'PORTO FRANCO': { name: 'Deoclídes', gender: 'M' },
  'AMARANTE DO MARANHÃO': { name: 'Vanderly', gender: 'F' },
  'MONTES ALTOS': { name: 'Domingos França', gender: 'M' },
  'JOÃO LISBOA': { name: 'Dr. Fábio Holanda', gender: 'M' },
  'SENADOR LA ROCQUE': { name: 'Professor Bartolomeu', gender: 'M' },
  'DAVINÓPOLIS': { name: 'Zé Pequeno', gender: 'M' },
  'GOVERNADOR EDISON LOBÃO': { name: 'Fábio Soares', gender: 'M' },
  'PEDREIRAS': { name: 'Vanessa Maia', gender: 'F' },
  'PRESIDENTE DUTRA': { name: 'Raimundinho da Audiolar', gender: 'M' },
  'COLINAS': { name: 'Renato Santos', gender: 'M' },
  'SÃO MATEUS DO MARANHÃO': { name: 'Miltinho Aragão', gender: 'M' },
  'DOM PEDRO': { name: 'Galego Mota', gender: 'M' },
  'TUNTUM': { name: 'Fernando Pessoa', gender: 'M' },
  'GONÇALVES DIAS': { name: 'Suane Dias', gender: 'F' },
  'GOVERNADOR ARCHER': { name: 'Professora Leide', gender: 'F' },
  'CAXIAS': { name: 'Gentil Neto', gender: 'M' },
  'TIMON': { name: 'Rafael', gender: 'M' },
  'CODÓ': { name: 'Chiquinho FC', gender: 'M' },
  'COELHO NETO': { name: 'Bruno Silva', gender: 'M' },
  'ALDEIAS ALTAS': { name: 'Kedson', gender: 'M' },
  'PARNARAMA': { name: 'Juvenal Silva', gender: 'M' },
  'MATÕES': { name: 'Nonatinho', gender: 'M' },
  'SÃO FRANCISCO DO MARANHÃO': { name: 'Francisco do Posto', gender: 'M' },
  'BACABAL': { name: 'Roberto Costa', gender: 'M' },
  'COROATÁ': { name: 'Edimar Vaqueiro', gender: 'M' },
  'BALSAS': { name: 'Allan da Marissol', gender: 'M' },
  'CAROLINA': { name: 'Jayme Fonseca', gender: 'M' },
  'RIACHÃO': { name: 'Paula Coelho', gender: 'F' },
  'SÃO RAIMUNDO DAS MANGABEIRAS': { name: 'Accioly', gender: 'M' },
  'LORETO': { name: 'Germano Coelho', gender: 'M' },
  'SAMBAÍBA': { name: 'Fátima Dantas', gender: 'F' },
  'ALTO PARNAÍBA': { name: 'Rubens Japonês', gender: 'M' },
  'ALTO ALEGRE DO MARANHÃO': { name: 'Nilsilene do Liorne', gender: 'F' },
  'ARAIOSES': { name: 'Neto Carvalho', gender: 'M' },
  'ARAME': { name: 'Pedro Fernandes', gender: 'M' },
  'ARARI': { name: 'Simplesmente Maria', gender: 'F' },
  'BOM JARDIM': { name: 'Cristiane Varão', gender: 'F' },
  'BREJO': { name: 'Thâmara Castro', gender: 'F' },
  'BURITI': { name: 'André Gaúcho', gender: 'M' },
  'ICATU': { name: 'Wallace', gender: 'M' },
  'LAGO DA PEDRA': { name: 'Maura Jorge', gender: 'F' },
  'MIRANDA DO NORTE': { name: 'Ivaldo Ribeiro', gender: 'M' },
  'PENALVA': { name: 'Guerra', gender: 'M' },
  'PINDARÉ-MIRIM': { name: 'Dr. Alexandre', gender: 'M' },
  'SANTA INÊS': { name: 'Felipe dos Pneus', gender: 'M' },
  'SANTA LUZIA': { name: 'Jucelino Marreca', gender: 'M' },
  'SANTA QUITÉRIA DO MARANHÃO': { name: 'Sâmia Moreira', gender: 'F' },
  'SÃO BERNARDO': { name: 'Chico Carvalho', gender: 'M' },
  'SÃO DOMINGOS DO MARANHÃO': { name: 'Kleber Tratorzão', gender: 'M' },
  'TIMBIRAS': { name: 'Paulo Vinicius', gender: 'M' },
  'URBANO SANTOS': { name: 'Professor Clemilton Barros', gender: 'M' },
  'VARGEM GRANDE': { name: 'Preto', gender: 'M' },
  'VITÓRIA DO MEARIM': { name: 'Nato da Nordestina', gender: 'M' },
  'ZÉ DOCA': { name: 'Flavinha Cunha', gender: 'F' },
};
